package life.wpx1997.community.mapper;

import java.util.List;
import life.wpx1997.community.model.CommunityLike;
import life.wpx1997.community.model.CommunityLikeExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CommunityLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_like
     *
     * @mbg.generated Mon Jul 27 23:32:45 CST 2020
     */
    long countByExample(CommunityLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_like
     *
     * @mbg.generated Mon Jul 27 23:32:45 CST 2020
     */
    int deleteByExample(CommunityLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_like
     *
     * @mbg.generated Mon Jul 27 23:32:45 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_like
     *
     * @mbg.generated Mon Jul 27 23:32:45 CST 2020
     */
    int insert(CommunityLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_like
     *
     * @mbg.generated Mon Jul 27 23:32:45 CST 2020
     */
    int insertSelective(CommunityLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_like
     *
     * @mbg.generated Mon Jul 27 23:32:45 CST 2020
     */
    List<CommunityLike> selectByExampleWithRowbounds(CommunityLikeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_like
     *
     * @mbg.generated Mon Jul 27 23:32:45 CST 2020
     */
    List<CommunityLike> selectByExample(CommunityLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_like
     *
     * @mbg.generated Mon Jul 27 23:32:45 CST 2020
     */
    CommunityLike selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_like
     *
     * @mbg.generated Mon Jul 27 23:32:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") CommunityLike record, @Param("example") CommunityLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_like
     *
     * @mbg.generated Mon Jul 27 23:32:45 CST 2020
     */
    int updateByExample(@Param("record") CommunityLike record, @Param("example") CommunityLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_like
     *
     * @mbg.generated Mon Jul 27 23:32:45 CST 2020
     */
    int updateByPrimaryKeySelective(CommunityLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_like
     *
     * @mbg.generated Mon Jul 27 23:32:45 CST 2020
     */
    int updateByPrimaryKey(CommunityLike record);
}